contentColumnType: string
fieldGroup: f445487e-f6a2-471c-a08b-3096f57da2d0
handle: teaserImage
instructions: ''
name: 'Teaser Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:7c831f23-da90-4f0d-90a2-454375ee2e8e'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add image to use in homepage/listing page teaser.'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:7c831f23-da90-4f0d-90a2-454375ee2e8e'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:33c8318a-f8ad-43f7-8231-448c204a6ed9'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
