enableVersioning: true
handle: podcast
name: Podcast
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  35c13b6c-aaee-499a-9580-96963583b7f4: # Downlink
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: 'podcast/{slug}'
type: channel
